import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";

import SessionProvider from "./components/SessionProvider";
import NavMenu from "./components/NavMenu";
import { getServers } from "dns";
import { Toaster } from "react-hot-toast";
import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Budget Buddy",
  description: "Generated by create next app, made by YANGXDEV",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <Head>
        <link href="https://fonts.cdnfonts.com/css/nexa" rel="stylesheet" />
      </Head>
      <body className="dark">
        <SessionProvider session={session}>
          <main className="flex flex-row">
            <NavMenu />
            <div className="bg-[#161616] flex-grow p-dashboard-padding h-screen">
              {children}
              <Toaster position="top-right" reverseOrder={false} />
            </div>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
